version: '3.4'

services:
  gogs:
    container_name: gogs_app
    tty: true
    stdin_open: true
    restart: always
    build:
      context: .
    depends_on:
      - postgres
    networks:
      gogs_network:
        ipv4_address: 10.30.12.10
  postgres:
    image: postgres:15.3-alpine
    container_name: gogs_postgres
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      gogs_network:
        ipv4_address: 10.30.12.11


volumes:
  db_data:
    driver: local
  files:
    driver: local

networks:
  gogs_network:
    ipam:
      config:
        - subnet: 10.30.12.0/24
